stages:
  - checks

.checks: &checks
  image: rust:1.78.0-alpine3.19
  stage: checks
  before_script:
    - apk add --no-cache build-base
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/
      - ~/.cargo

format:
  <<: *checks
  script:
    - rustup component add rustfmt
    - cargo fmt --check --all --verbose

test:
  <<: *checks
  script: cargo test --verbose

clippy:
  <<: *checks
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

build:
  <<: *checks
  script: cargo build --verbose
